env:
    MANIFEST: https://github.com/Project-Awaken/android_manifest -b triton --git-lfs --depth=1
    DEVICE: RMX1901
    OEM: realme
    LOCAL_MANIFEST: https://github.com/ij-israfil/local_manifest.git -b aw
    TARGET: bacon
    LUNCH_COMBO: awaken_${DEVICE}-userdebug
    OUTPUT: a*.zip
    #CLO: Drive3:Awaken
    #CLO_1: ENCRYPTED[!584b549b7e1c7497c082e4d6e651f4b0008588b42560261fb5f9403d605095512d3ca0791166992f4a3bc13a3a71cd38!]
    URI: ENCRYPTED[!81e05d020399f6f6939800f7831c54a0c671f8fc2ad821d41068099ffe5136ae7f09d2f894a1ef1e0cd07934689855cb!]
    ROM_U: 1
    
task:
  name: "build"
  timeout_in: 119m
  container:
      #image: apon77/aosp:cirrus
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
