env:
    MANIFEST: https://github.com/RisingTechOSS/android -b thirteen --git-lfs --depth=1
    DEVICE: RMX1901
    OEM: realme
    LOCAL_MANIFEST: https://github.com/ij-israfil/local_manifest.git -b rr
    TARGET: bacon
    LUNCH_COMBO: lineage_${DEVICE}-userdebug
    OUTPUT: r*.zip
    CLO: Drive3:Rise
    CLO_1: ENCRYPTED[!584b549b7e1c7497c082e4d6e651f4b0008588b42560261fb5f9403d605095512d3ca0791166992f4a3bc13a3a71cd38!]
    URI: https://sourceforge.net/projects/realme-x-1901/files/ccache/Rise/ccache.tar.gz/download
    ROM_U: 0
    
task:
  name: "build"
  timeout_in: 2h
  container:
      #image: apon77/aosp:cirrus
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
